### ISSUE TITLE
latest release azure databricks  TypeError: missing a required argument: 'spark'

### ISSUE THREAD

**Issue by Freewilly3d** [moj-analytical-services/splink_demos#10]
prior release did not require 

from utility_functions.demo_utils import get_spark
spark = get_spark() # See utility_functions/demo_utils.py for how to set up Spark

in azure databricks spark is set to 
print(spark)
<pyspark.sql.session.SparkSession object at 0x7f29a3a3d940>

by default

**Comment by Freewilly3d** [comment]
didn't realize the parameters for splink changed

**Comment by EdLucio** [comment]
> didn't realize the parameters for splink changed

Hi, what was your solution to this?
