### ISSUE TITLE
ModuleNotFoundError: No module named 'splink.duckdb'

### ISSUE THREAD

**Issue by msiemionCalistapw** [moj-analytical-services/splink_demos#54]
Hi Robin,

Very excited about your Splink code! I tried to run the Quickstart code in jupyter notebook and ran into a no module error for the following line of code: 

from splink.duckdb.duckdb_linker import DuckDBLinker
from splink.duckdb.duckdb_comparison_library import (
    exact_match,
    levenshtein_at_thresholds,

 .....

Please let me know if you can help with the setup of splink modules for record linkage.

Thanks,

Michayla

**Comment by ThomasHepworth** [comment]
Hiya 👋

If you just want to play around with splink and our demo examples, you can use the binder link which will boot up a jupyterlab window w/ the required modules:

 [![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/moj-analytical-services/splink_demos/splink3_demos?urlpath=lab)

If you particularly want to run `splink` locally in jupyter, it sounds like you'll need to set up a kernel. It's a bit of a pain/slightly daunting if you haven't done so before, unfortunately.

I'd need to know your OS and what you use to create virtual environments to give you a specific set of instructions.

In lieu of that, you can check out the python guide on [venvs](https://docs.python.org/3/library/venv.html) for some basic info on setting something up.

If you can get that working, you simply need to use the following in the terminal to create a kernel (renaming the kernel):
```
pip install ipykernel
python -m ipykernel install --user -–name=<name_of_kernel>
```

**Comment by ThomasHepworth** [comment]
Oh, I completely forgot I updated the README a while ago too.

Some info on setting up your environment can be found [here](https://github.com/moj-analytical-services/splink_demos#running-these-notebooks-locally-in-vscode).

**Comment by msiemionCalistapw** [comment]
Hi there, thanks for all of the info! I have created a virtual environment via anaconda prompt and successfully activated in Jupyter. The I went into myenv in Jupyter and tried the code again and am getting the same no module found error :/  I must be doing something wrong but I'm not sure what. working on windows btw!

**Comment by ThomasHepworth** [comment]
Are you setting your kernel inside the jupyter terminal?

![Screenshot 2022-08-04 at 10 06 29](https://user-images.githubusercontent.com/45356472/182809050-c00bec3a-96ea-4c14-97db-5566b38b43c7.png)

**Comment by msiemionCalistapw** [comment]
Sorry, I'll give you some more info! So i set up virtual invironment in anaconda prompt using:
conda create -n myenv python=3.9
conda activate myenv
pip install --user ipykernel
python -m ipykernel install --user --name=myenv

then in Jupyter... 
![image](https://user-images.githubusercontent.com/110547718/182826345-9dbd8574-6d5a-437b-9495-b06d7da9b09e.png)
<img width="721" alt="envJupe" src="https://user-images.githubusercontent.com/110547718/182826429-0742e73b-a7db-4f54-ad20-6c58d8660fb5.PNG">

**Comment by ThomasHepworth** [comment]
Ah, I think I know why then, thanks. It looks like we haven't updated our [conda release](https://anaconda.org/conda-forge/splink) for over a year now, so I'm guessing it's simply down to that.

Can you check which version of splink you've currently got installed?

**Comment by msiemionCalistapw** [comment]
looks like 2.1.14

![image](https://user-images.githubusercontent.com/110547718/182834530-89591eb7-925a-4412-8255-3f496d4f9525.png)

**Comment by ThomasHepworth** [comment]
Ah perfect, thanks for bringing this to our attention. We'll try to update it over the next week.

For now, can you pip install splink so you can use the latest version.
`%pip install splink -U`

**Comment by msiemionCalistapw** [comment]
That did it! Thank you so much! 

Just curious… what is the reasoning for needing the virtual environment?

**Comment by ThomasHepworth** [comment]
For the most part, it's just for better package management.

In short, package Management software:
* Records installed packages of the original user.
* Records versions of these packages.
* And manages package dependency conflicts.

This helps ensure your code is reproducible in both the present and the future. It also means projects don't get cluttered by unnecessary packages as easily.

For the jupyter case, it also means you don't have to reinstall the packages every time the kernel gets restarted.

**Comment by msiemionCalistapw** [comment]
makes sense, thanks!!
