### ISSUE TITLE
Invalid Input Error: Levenshtein Function: 2nd argument too short

### ISSUE THREAD

**Issue by msiemionCalistapw** [moj-analytical-services/splink_demos#55]
I am running the example model on my own data source and am getting this error "RuntimeError: Invalid Input Error: Levenshtein Function: 2nd argument too short" 

my comparison settings are this:  levenshtein_at_thresholds("Claim_description", 2),

looks like the codes is also failing on this line:  linker.estimate_u_using_random_sampling(target_rows=1e6)

**Comment by ThomasHepworth** [comment]
Heya, could you post any questions or queries you have [here](https://github.com/moj-analytical-services/splink/discussions) please.

Thanks!

**Comment by RobinL** [comment]
See https://github.com/moj-analytical-services/splink/discussions/699#discussioncomment-3351927
